
sources:


- name: raw
  schema: gz_raw_dataset
  tables:
    - name: sales
      identifier: raw_gz_sales
      description: sales info
    - name: product
      identifier: raw_gz_product
      description: product information
      columns:
        - name: products_id
          tests:
          - unique
          
    - name: ship
      identifier: raw_gz_ship
